export { default as Navbar } from './navbar/navbar';
export { default as Main } from './main/main';
export { default as Footer } from './footer/footer';
export { default as Contact } from './contact/contact';
export { default as Login } from './login/login';
export { default as Register } from './register/register';
export { default as About } from './about/about'
export { default as Clients } from './clients/clients'
export { default as Process } from './process/process'
export { default as Services } from './services/services'